# Data Analytics on my Job Search

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data = pd.read_csv('job_applications_final.csv')
data.head()

,application_date,company,job_title,platform,response_date,response_status
0,2026-04-24,AI Report,AI/ML Engineer,LinkedIn,2026-04-24,Received
1,2026-04-28,ASAP Consulting,ML/AI Engineer and Data Scientist,Direct Email,NaN,Received
2,2026-04-28,ASAP Consulting,ML/AI Engineer y Data Scientist,Direct Email,NaN,Received
3,2026-03-25,Accenture,Academy Sr AI,Direct Email,2026-03-25,Received
4,2026-04-27,Accenture,Consulting Specialist,LinkedIn,2026-04-27,Received

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 278 entries, 0 to 277
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   application_date  275 non-null    str
 1   company           278 non-null    str
 2   job_title         247 non-null    str
 3   platform          278 non-null    str
 4   response_date     134 non-null    str
 5   response_status   278 non-null    str
dtypes: str(6)
memory usage: 13.2 KB

In [9]:
data["application_date"] = pd.to_datetime(data["application_date"], format="mixed")
data["response_date"] = pd.to_datetime(data["response_date"], errors='coerce')
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 278 entries, 0 to 277
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   application_date  275 non-null    datetime64[us]
 1   company           278 non-null    str
 2   job_title         247 non-null    str
 3   platform          278 non-null    str
 4   response_date     133 non-null    datetime64[us]
 5   response_status   278 non-null    str
dtypes: datetime64[us](2), str(4)
memory usage: 13.2 KB

In [16]:
data.response_status.value_counts()

response_status
Received           194
No Response         47
Rejected            23
Interview            5
Technical Test       4
Update Received      2
In Progress          1
Questionnaire        1
Not Applicable       1
Name: count, dtype: int64

In [25]:
repeated = (data.job_title.isna() & data.duplicated(subset="company"))

In [27]:
data = data[~repeated]

In [29]:
data.query('response_status != "Received" & response_date.isna()')

,application_date,company,job_title,platform,response_date,response_status
6,2026-04-20,Accenture,Data Scientist,Workday,NaT,Rejected
19,2026-04-20,AceUp,AI/ML Engineer,Silver.dev,NaT,No Response
27,2026-04-20,Anyone AI,AI/ML Engineer,LinkedIn,NaT,No Response
35,2026-04-26,BYMA,NaN,LinkedIn,NaT,No Response
41,2026-04-27,Banco Macro,Data Scientist,LinkedIn,NaT,No Response
44,2026-04-27,Beeflow,AI Ops & Business Analyst,Workable,NaT,In Progress
58,2026-04-29,Bumeran,Python Software Engineer,Bumeran,NaT,No Response
61,2026-04-20,Canals,AI/ML Engineer,LinkedIn,NaT,No Response
71,2026-04-20,Central Puerto,AI/ML Engineer,LinkedIn,NaT,No Response
78,2026-04-20,Cocos,AI/ML Engineer,LinkedIn,NaT,No Response
112,2026-04-29,Dev.Pro,Vibe Coder (AI-Assisted Software Engineer / Fu...,Workable,NaT,Interview
113,2026-04-20,DevRev,AI/ML Engineer,LinkedIn,NaT,No Response
115,2026-04-20,Dialpad,AI/ML Engineer,LinkedIn,NaT,No Response
121,2026-04-27,EPAM Systems,Data Science Engineer (AWS SageMaker & Bedrock),Glassdoor,NaT,Not Applicable
129,2026-04-01,Experis,NaN,LinkedIn,NaT,No Response
148,2026-04-07,INDI Staffing,NaN,LinkedIn,NaT,No Response
154,2026-04-20,ITSM Consulting,AI/ML Engineer,LinkedIn,NaT,No Response
158,2026-04-20,Innodata,NaN,LinkedIn,NaT,No Response
165,2026-04-21,JPMorgan,Data Analytics Associate,Oracle,NaT,Update Received
177,2026-04-08,Laboratorios Jayor,NaN,LinkedIn,NaT,No Response
181,2026-04-25,Marval,NaN,LinkedIn,NaT,No Response
184,2026-04-20,Mercado Libre,AI/ML Engineer,LinkedIn,NaT,No Response
192,2026-04-20,Movimiento CREA,AI/ML Engineer,LinkedIn,NaT,No Response
201,2026-04-20,Nosis,AI/ML Engineer,LinkedIn,NaT,No Response
203,2026-04-10,NotCo AI,NaN,LinkedIn,NaT,No Response
226,2026-03-19,Pyramid Consulting,NaN,LinkedIn,NaT,No Response
231,2026-04-20,Rappi,AI Engineer,Direct Email,NaT,Technical Test
237,2026-03-12,Scale AI,Remote Coding Expertise for AI Training,Direct Email,NaT,Interview
247,2026-04-20,TCS,AI/ML Engineer,LinkedIn,NaT,No Response
252,2026-04-20,ThinkBig HR,AI/ML Engineer,LinkedIn,NaT,No Response
260,2026-04-20,Vicente Lopez,AI/ML Engineer,LinkedIn,NaT,No Response
263,2026-04-20,Waves,AI/ML Engineer,LinkedIn,NaT,No Response

In [30]:
data.query('response_status == "Received"')

,application_date,company,job_title,platform,response_date,response_status
0,2026-04-24,AI Report,AI/ML Engineer,LinkedIn,2026-04-24,Received
1,2026-04-28,ASAP Consulting,ML/AI Engineer and Data Scientist,Direct Email,NaT,Received
2,2026-04-28,ASAP Consulting,ML/AI Engineer y Data Scientist,Direct Email,NaT,Received
3,2026-03-25,Accenture,Academy Sr AI,Direct Email,2026-03-25,Received
4,2026-04-27,Accenture,Consulting Specialist,LinkedIn,2026-04-27,Received
...,...,...,...,...,...,...
268,2026-02-05,Xometry,Machine Learning Engineer II,LinkedIn,NaT,Received
270,2026-04-26,Y Combinator,Job Title Not Specified,Workable,2026-04-26,Received
271,2026-03-13,Yumatech,Data Analyst,LinkedIn,NaT,Received
272,2026-04-29,belo,Juan,Silver.dev,2026-04-29,Received
273,2026-04-20,hiberus,IA Engineer,LinkedIn,NaT,Received